name: "Code Review AI"
description: "Perform a code review on code modified using Ollama"
inputs:
  llm-model:
    description: "Name of the LLM model to use for code review"
    required: true
    default: "llama3.2"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: "Setup jq"
      uses: dcarbone/install-jq-action@v2
      with:
        version: "1.7"
        force: "false"

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | bash
        ollama serve & ollama pull ${{ inputs.llm-model }}
      shell: bash

    - name: Get modified files
      id: get-modified-files
      uses: tj-actions/changed-files@v43

    - name: Review modified files
      env:
        GITHUB_TOKEN: ${{ github.token }}
        LLM_MODEL: ${{ inputs.llm-model }}
      run: |
        bash ${{ github.action_path }}/review_script.sh
      shell: bash
