name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd .github/actions/ai_code_review
          npm install

      - name: Build project
        run: |
          cd .github/actions/ai_code_review
          npm run build

      - name: Start Ollama server
        run: |
          curl https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 10  # Give some time for the server to start

      - name: Pull Ollama model
        run: ollama pull llama3.2

      - name: Run AI Code Review
        uses: ./.github/actions/ai_code_review
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          debug: "true"
          ollama_light_model: "llama3.2"
          ollama_heavy_model: "llama3.2"
          language: "ko"

      - name: Stop Ollama server
        if: always()
        run: pkill ollama
