name: add tag

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch"
        required: true
      tag:
        description: "tag"
        required: true

env:
  BRANCH: ${{ github.event.inputs.branch }}
  TAG: ${{ github.event.inputs.tag }}

jobs:
  test_git:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Switch branch
        run: |
          git pull
          git switch ${{ env.BRANCH }}

      - name: Add tag
        run: |
          git config --global user.name "baekteun"
          git config --global user.email "baegteun@gmail.com"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          CUSTOM_TAG: ${{ env.TAG }}

          # TAG_NAME="${{ env.TAG }}"
          # git tag -a "$TAG_NAME" -m ""
          # git push https://baekteun:${{ env.GH_TOKEN }}@github.com/github-action-workflow-test.git
          # git push origin "$TAG_NAME"
