name: git test

on: workflow_dispatch

jobs:
  test_git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Git
        continue-on-error: true
        run: |
          git pull
          git branch -D feature/test-git

      - name: Test Git 2
        run: |
          git switch feature/test-git

          echo "success to git test"
