name: "On Tag"

env:
  SERVICE: LogoMaker
  CONFIGURATION: Release

on:
  push:
    tags:
      - release-v*

jobs:
  on_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo success
        run: "success to trigger on tag"
